# Generated by Django 2.1.2 on 2018-10-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='question_branch',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_section',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_year',
            field=models.IntegerField(null=True),
        ),
    ]
