# Generated by Django 2.1.2 on 2018-10-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181022_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
    ]
