# Generated by Django 2.1.2 on 2018-10-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20181022_0957'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_year', 'question_branch', 'question_section')},
        ),
    ]
