# Generated by Django 2.1.2 on 2018-11-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181105_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Tag',
            field=models.CharField(default='Vote Independently', max_length=200, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Name',
            field=models.CharField(max_length=20, verbose_name='Candidate Name'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('Name', 'votes')},
        ),
    ]
