# Generated by Django 2.1.2 on 2018-11-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181111_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='posters',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
    ]
