# Generated by Django 2.1.1 on 2018-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_users_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='branch',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='users',
            name='section',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
