# Generated by Django 2.1.1 on 2018-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_auto_20181001_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='branch',
            field=models.CharField(max_length=2),
        ),
    ]
