# Generated by Django 2.1.1 on 2018-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0005_auto_20181007_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roll',
            field=models.CharField(max_length=8),
        ),
    ]
