# Generated by Django 2.1.1 on 2018-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0006_auto_20181007_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roll',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
