# Generated by Django 2.1.1 on 2018-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_auto_20181007_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='section',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
