# Generated by Django 2.1.1 on 2018-11-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0011_auto_20181029_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
