# Generated by Django 2.1.1 on 2018-11-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0014_auto_20181103_1640'),
        ('council', '0012_auto_20181103_1932'),
    ]

    operations = [
    ]
