# Generated by Django 2.1.1 on 2018-11-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('council', '0015_merge_20181104_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('convenor', models.CharField(max_length=256)),
                ('no_of_members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField(editable=False)),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_club', to='council.Club')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_club', to='council.Club')),
            ],
        ),
    ]
