# Generated by Django 2.1.1 on 2018-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0016_club_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.CharField(default='Project funding', max_length=256),
            preserve_default=False,
        ),
    ]
