# Generated by Django 2.1.1 on 2018-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0017_transaction_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('summary', models.TextField()),
                ('detail', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
